In [20]:
import earthnet as en
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

for dirname1 in os.listdir(r"C:\Users\jeroe\Documents\Masterthesis\weather2land\code\data\en21ds_full\iid_test_split\target"):
    string1 = os.path.basename(dirname1)
    L1_T = np.arange(5, 105, 5)
    ListAVG = []
    Location = []
    TimeSeriesDF = pd.DataFrame(columns=L1_T)

    for dirname in os.listdir(r"C:\Users\jeroe\Documents\Masterthesis\weather2land\code\data\en21ds_full\iid_test_split\target\\" + string1):

        string = os.path.basename(dirname)
        sample1 = np.load(r"C:\Users\jeroe\Documents\Masterthesis\weather2land\code\data\en21ds_full\iid_test_split\target\\"+ string1 + "\\" + string)
        hrd1 = sample1["highresdynamic"]
        imgs1 = hrd1[:,:,3,:]
        Location.append(string)


        avg = np.nanmean(imgs1,axis=(0, 1))
        ListAVG.append(avg)
        #print(avg.shape)

    for averag in ListAVG:    
        TimeSeriesDF.loc[len(TimeSeriesDF)] = averag

    TimeSeriesDF['Location'] = Location  
    output = r"C:\Users\jeroe\Documents\Masterthesis\weather2land\code\src\models\pt_convlstm\\" + string1 + ".csv"
    TimeSeriesDF.to_csv(output, index=False)
    print('----------------------------------------------')
    print('exported the Dataframe to csv of the following Tile:', string1)
    print('----------------------------------------------')
    

    





C:\Users\jeroe\AppData\Local\Temp\ipykernel_5668\481800546.py:23: RuntimeWarning: Mean of empty slice
  avg = np.nanmean(imgs1,axis=(0, 1))


----------------------------------------------
exported the Dataframe to csv of the following Tile: 29SND
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of the following Tile: 29SPC
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of the following Tile: 29SQB
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of the following Tile: 29TNE
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of the following Tile: 29TPE
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of the following Tile: 29TPH
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of th

In [14]:
a = (np.arange(12)).reshape(4,3)
print(np.mean(a, axis=1), a)


[ 1.  4.  7. 10.] [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [22]:
import earthnet as en
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

for dirname1 in os.listdir(r"C:\Users\jeroe\Documents\Masterthesis\weather2land\code\data\en21ds_full\iid_test_split\target"):
    string1 = os.path.basename(dirname1)
    L1_T = np.arange(5, 105, 5)
    ListAVG = []
    Location = []
    TimeSeriesDF = pd.DataFrame(columns=L1_T)

    for dirname in os.listdir(r"C:\Users\jeroe\Documents\Masterthesis\weather2land\code\data\en21ds_full\iid_test_split\target\\" + string1):

        string = os.path.basename(dirname)
        sample1 = np.load(r"C:\Users\jeroe\Documents\Masterthesis\weather2land\code\data\en21ds_full\iid_test_split\target\\"+ string1 + "\\" + string)
        hrd1 = sample1["highresdynamic"]
        imgs1 = hrd1[:,:,3,:]
        Location.append(string)

        pixelwisestd = np.nanstd(imgs1,axis=0)
        meanstdperframe = np.nanmean(pixelwisestd,axis=0)

        ListAVG.append(meanstdperframe)

    for averag in ListAVG:    
        TimeSeriesDF.loc[len(TimeSeriesDF)] = averag

    TimeSeriesDF['Location'] = Location  
    output = r"C:\Users\jeroe\Documents\Masterthesis\weather2land\code\src\models\pt_convlstm\\" + string1 + "_std.csv"
    TimeSeriesDF.to_csv(output, index=False)
    print('----------------------------------------------')
    print('exported the Dataframe to csv of the following Tile:', string1)
    print('----------------------------------------------')

C:\Users\jeroe\AppData\Local\Temp\ipykernel_5668\2061977355.py:23: RuntimeWarning: Mean of empty slice
  meanstdperframe = np.nanmean(pixelwisestd,axis=0)


----------------------------------------------
exported the Dataframe to csv of the following Tile: 29SND
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of the following Tile: 29SPC
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of the following Tile: 29SQB
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of the following Tile: 29TNE
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of the following Tile: 29TPE
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of the following Tile: 29TPH
----------------------------------------------
----------------------------------------------
exported the Dataframe to csv of th